#!/usr/bin/env python3
"""Day 6: Reading Sequencing Data — Python equivalent.

FASTQ quality control pipeline using Biopython and numpy.
Requires: examples/sample.fastq (generated by init.bl)
"""

import os
import numpy as np
from Bio import SeqIO
from Bio.SeqUtils import gc_fraction
from collections import Counter

print("=" * 60)
print("Day 6: FASTQ Quality Control Pipeline (Python)")
print("=" * 60)

# ============================================================
# 1. RAW DATA SUMMARY
# ============================================================
print("\n--- 1. Raw Data Summary ---")

records = list(SeqIO.parse("examples/sample.fastq", "fastq"))
total_reads = len(records)
total_bases = sum(len(r.seq) for r in records)
mean_length = total_bases / total_reads
qualities = [np.mean(r.letter_annotations["phred_quality"]) for r in records]
mean_quality = np.mean(qualities)
gc_values_all = [gc_fraction(r.seq) for r in records]
gc_content = np.mean(gc_values_all)

print(f"Total reads: {total_reads}")
print(f"Total bases: {total_bases}")
print(f"Mean length: {round(mean_length, 1)}")
print(f"Mean quality: {round(mean_quality, 1)}")
print(f"GC content: {round(gc_content * 100, 1)}%")

# ============================================================
# 2. PER-READ QUALITY ANALYSIS
# ============================================================
print("\n--- 2. Per-Read Quality Analysis ---")

print(f"Quality range: {round(min(qualities), 1)} - {round(max(qualities), 1)}")
print(f"Mean quality: {round(np.mean(qualities), 1)}")

# Quality distribution (text histogram)
bins = [(10, 15), (15, 20), (20, 25), (25, 30), (30, 35), (35, 40)]
print("\nQuality Distribution")
for low, high in bins:
    count = sum(1 for q in qualities if low <= q < high)
    bar = "#" * count
    print(f"  Q{low}-{high}: {bar:<20} ({count})")

# ============================================================
# 3. LENGTH DISTRIBUTION
# ============================================================
print("\n--- 3. Length Distribution ---")

lengths = [len(r.seq) for r in records]
print(f"Length range: {min(lengths)} - {max(lengths)}")
print(f"Mean length: {round(np.mean(lengths), 1)}")
short_count = sum(1 for l in lengths if l < 50)
print(f"Short reads (< 50 bp): {short_count}")

# ============================================================
# 4. STANDARD FILTERING
# ============================================================
print("\n--- 4. Standard Filtering ---")

clean = [r for r in records
         if len(r.seq) >= 50
         and np.mean(r.letter_annotations["phred_quality"]) >= 20]

print(f"Before: {len(records)} reads")
print(f"After:  {len(clean)} reads")
print(f"Kept:   {round(len(clean) / len(records) * 100, 1)}%")

# ============================================================
# 5. CUSTOM FILTERING (length + quality + GC)
# ============================================================
print("\n--- 5. Custom Filtering (length + quality + GC) ---")

strict_clean = [r for r in records
                if len(r.seq) >= 50
                and np.mean(r.letter_annotations["phred_quality"]) >= 20
                and 0.2 < gc_fraction(r.seq) < 0.8]

print(f"After all filters: {len(strict_clean)} reads")

# ============================================================
# 6. QUALITY TRIMMING
# ============================================================
print("\n--- 6. Quality Trimming ---")

def trim_quality(record, min_qual=20, window=5):
    """Trim low-quality bases from 3' end using sliding window."""
    quals = record.letter_annotations["phred_quality"]
    end = len(quals)
    while end > window:
        window_avg = np.mean(quals[end - window:end])
        if window_avg >= min_qual:
            break
        end -= 1
    return record[:end]

trimmed = [trim_quality(r, min_qual=20) for r in records]
original_mean = np.mean([len(r.seq) for r in records])
trimmed_mean = np.mean([len(r.seq) for r in trimmed])

print(f"Mean length before: {round(original_mean, 1)}")
print(f"Mean length after:  {round(trimmed_mean, 1)}")

# ============================================================
# 7. ADAPTER DETECTION
# ============================================================
print("\n--- 7. Adapter Detection ---")

# Simple adapter detection: look for common adapter sequences
common_adapters = [
    ("Illumina TruSeq", "AGATCGGAAGAGC"),
    ("Nextera", "CTGTCTCTTATACACATCT"),
]

detected = []
for name, adapter in common_adapters:
    count = sum(1 for r in records if adapter in str(r.seq))
    if count > 0:
        detected.append(adapter)
        print(f"  {name}: found in {count} reads")

print(f"Detected adapters: {detected}")

# ============================================================
# 8. K-MER ANALYSIS
# ============================================================
print("\n--- 8. K-mer Analysis ---")

first_seq = str(records[0].seq)
k = 5
kmers = Counter()
for i in range(len(first_seq) - k + 1):
    kmers[first_seq[i:i + k]] += 1

print(f"5-mers found in first read: {len(kmers)}")
print("Top 10 most frequent 5-mers:")
print(f" {'kmer':<8} | count")
for kmer, count in kmers.most_common(10):
    print(f" {kmer:<8} | {count}")

# ============================================================
# 9. CLEAN READ QUALITY SUMMARY
# ============================================================
print("\n--- 9. Clean Read Quality Summary ---")

clean_quals = [np.mean(r.letter_annotations["phred_quality"]) for r in clean]
print(f"Clean read mean quality: {round(np.mean(clean_quals), 1)}")
print(f"Clean read min quality:  {round(min(clean_quals), 1)}")

gc_clean = [gc_fraction(r.seq) for r in clean]
print(f"Clean read mean GC: {round(np.mean(gc_clean) * 100, 1)}%")

# ============================================================
# 10. WRITE OUTPUT
# ============================================================
print("\n--- 10. Write Clean Reads ---")

os.makedirs("results", exist_ok=True)
with open("results/clean_reads.fastq", "w") as out:
    SeqIO.write(clean, out, "fastq")
print(f"Wrote {len(clean)} clean reads to results/clean_reads.fastq")

# Q30 metric
q30_count = sum(1 for q in qualities if q >= 30)
q30_pct = round(q30_count / total_reads * 100, 1)
print(f"Q30 reads: {q30_count}/{total_reads} ({q30_pct}%)")

print()
print("=" * 60)
print("Day 6 complete! Your first sequencing QC pipeline.")
print("=" * 60)
