#!/usr/bin/env Rscript
# Day 6: Reading Sequencing Data — R equivalent
#
# FASTQ quality control pipeline using ShortRead and Biostrings.
# Requires: examples/sample.fastq (generated by init.bl)

library(ShortRead, quietly = TRUE, warn.conflicts = FALSE)
library(Biostrings, quietly = TRUE, warn.conflicts = FALSE)

cat(strrep("=", 60), "\n")
cat("Day 6: FASTQ Quality Control Pipeline (R)\n")
cat(strrep("=", 60), "\n")

# ============================================================
# 1. RAW DATA SUMMARY
# ============================================================
cat("\n--- 1. Raw Data Summary ---\n")

fq <- readFastq("examples/sample.fastq")
total_reads <- length(fq)
seqs <- sread(fq)
quals <- quality(fq)
total_bases <- sum(width(seqs))
mean_length <- total_bases / total_reads

# Compute per-read mean quality
qual_matrix <- as(quals, "matrix")
per_read_quality <- rowMeans(qual_matrix, na.rm = TRUE)
mean_quality <- mean(per_read_quality)

# GC content
gc_content <- letterFrequency(seqs, letters = c("G", "C"))
gc_fraction <- rowSums(gc_content) / width(seqs)
mean_gc <- mean(gc_fraction)

cat(sprintf("Total reads: %d\n", total_reads))
cat(sprintf("Total bases: %d\n", total_bases))
cat(sprintf("Mean length: %.1f\n", mean_length))
cat(sprintf("Mean quality: %.1f\n", mean_quality))
cat(sprintf("GC content: %.1f%%\n", mean_gc * 100))

# ============================================================
# 2. PER-READ QUALITY ANALYSIS
# ============================================================
cat("\n--- 2. Per-Read Quality Analysis ---\n")

cat(sprintf("Quality range: %.1f - %.1f\n", min(per_read_quality), max(per_read_quality)))
cat(sprintf("Mean quality: %.1f\n", mean(per_read_quality)))

# Quality distribution
cat("\nQuality Distribution\n")
breaks <- c(10, 15, 20, 25, 30, 35, 40)
for (i in seq_len(length(breaks) - 1)) {
  count <- sum(per_read_quality >= breaks[i] & per_read_quality < breaks[i + 1])
  bar <- paste(rep("#", count), collapse = "")
  cat(sprintf("  Q%d-%d: %-20s (%d)\n", breaks[i], breaks[i + 1], bar, count))
}

# ============================================================
# 3. LENGTH DISTRIBUTION
# ============================================================
cat("\n--- 3. Length Distribution ---\n")

lengths <- width(seqs)
cat(sprintf("Length range: %d - %d\n", min(lengths), max(lengths)))
cat(sprintf("Mean length: %.1f\n", mean(lengths)))
short_count <- sum(lengths < 50)
cat(sprintf("Short reads (< 50 bp): %d\n", short_count))

# ============================================================
# 4. STANDARD FILTERING
# ============================================================
cat("\n--- 4. Standard Filtering ---\n")

keep <- lengths >= 50 & per_read_quality >= 20
clean <- fq[keep]

cat(sprintf("Before: %d reads\n", total_reads))
cat(sprintf("After:  %d reads\n", length(clean)))
cat(sprintf("Kept:   %.1f%%\n", length(clean) / total_reads * 100))

# ============================================================
# 5. CUSTOM FILTERING (length + quality + GC)
# ============================================================
cat("\n--- 5. Custom Filtering (length + quality + GC) ---\n")

strict_keep <- lengths >= 50 & per_read_quality >= 20 & gc_fraction > 0.2 & gc_fraction < 0.8
strict_clean <- fq[strict_keep]
cat(sprintf("After all filters: %d reads\n", length(strict_clean)))

# ============================================================
# 6. QUALITY TRIMMING
# ============================================================
cat("\n--- 6. Quality Trimming ---\n")

# ShortRead's trimTails: trim from right when quality < threshold
trimmed <- trimTails(fq, k = 1, a = "5", successive = TRUE)  # ASCII '5' = Q20
trimmed_lengths <- width(sread(trimmed))

cat(sprintf("Mean length before: %.1f\n", mean(lengths)))
cat(sprintf("Mean length after:  %.1f\n", mean(trimmed_lengths)))

# ============================================================
# 7. ADAPTER DETECTION
# ============================================================
cat("\n--- 7. Adapter Detection ---\n")

adapters <- c("AGATCGGAAGAGC", "CTGTCTCTTATACACATCT")
adapter_names <- c("Illumina TruSeq", "Nextera")
detected <- c()

for (i in seq_along(adapters)) {
  matches <- vcountPattern(adapters[i], seqs)
  count <- sum(matches > 0)
  if (count > 0) {
    detected <- c(detected, adapters[i])
    cat(sprintf("  %s: found in %d reads\n", adapter_names[i], count))
  }
}

cat(sprintf("Detected adapters: %s\n", paste(detected, collapse = ", ")))

# ============================================================
# 8. K-MER ANALYSIS
# ============================================================
cat("\n--- 8. K-mer Analysis ---\n")

first_seq <- as.character(seqs[1])
k <- 5
kmers <- substring(first_seq, 1:(nchar(first_seq) - k + 1),
                   k:nchar(first_seq))
kmer_table <- sort(table(kmers), decreasing = TRUE)

cat(sprintf("5-mers found in first read: %d\n", length(kmer_table)))
cat("Top 10 most frequent 5-mers:\n")
cat(sprintf(" %-8s | count\n", "kmer"))
top10 <- head(kmer_table, 10)
for (i in seq_along(top10)) {
  cat(sprintf(" %-8s | %d\n", names(top10)[i], top10[i]))
}

# ============================================================
# 9. CLEAN READ QUALITY SUMMARY
# ============================================================
cat("\n--- 9. Clean Read Quality Summary ---\n")

clean_quals_mat <- as(quality(clean), "matrix")
clean_per_read <- rowMeans(clean_quals_mat, na.rm = TRUE)
cat(sprintf("Clean read mean quality: %.1f\n", mean(clean_per_read)))
cat(sprintf("Clean read min quality:  %.1f\n", min(clean_per_read)))

clean_seqs <- sread(clean)
clean_gc <- rowSums(letterFrequency(clean_seqs, letters = c("G", "C"))) / width(clean_seqs)
cat(sprintf("Clean read mean GC: %.1f%%\n", mean(clean_gc) * 100))

# ============================================================
# 10. WRITE OUTPUT
# ============================================================
cat("\n--- 10. Write Clean Reads ---\n")

dir.create("results", showWarnings = FALSE)
writeFastq(clean, "results/clean_reads.fastq", compress = FALSE)
cat(sprintf("Wrote %d clean reads to results/clean_reads.fastq\n", length(clean)))

# Q30 metric
q30_count <- sum(per_read_quality >= 30)
q30_pct <- round(q30_count / total_reads * 100, 1)
cat(sprintf("Q30 reads: %d/%d (%.1f%%)\n", q30_count, total_reads, q30_pct))

cat("\n")
cat(strrep("=", 60), "\n")
cat("Day 6 complete! Your first sequencing QC pipeline.\n")
cat(strrep("=", 60), "\n")
