#!/usr/bin/env Rscript
# Day 7: Bioinformatics File Formats — R equivalent
# Run: Rscript scripts/analysis.R
# Requires: Rscript r/install.R
# Requires: data/ files (generated by init.bl or manually)

suppressPackageStartupMessages({
  library(Biostrings)
  library(GenomicRanges)
  library(rtracklayer)
})

cat(strrep("=", 60), "\n")
cat("Day 7: Bioinformatics File Formats (R)\n")
cat(strrep("=", 60), "\n")

# ============================================================
# 1. FASTA — REFERENCE SEQUENCES
# ============================================================
cat("\n--- 1. FASTA: Reference Sequences ---\n")

seqs <- readDNAStringSet("data/sequences.fasta")
cat(sprintf("Sequences: %d\n", length(seqs)))

for (i in seq_along(seqs)) {
  gc <- letterFrequency(seqs[[i]], letters = c("G", "C"))
  gc_pct <- sum(gc) / width(seqs[[i]]) * 100
  cat(sprintf("  %s: %d bp, GC=%.1f%%\n", names(seqs)[i], width(seqs[[i]]), gc_pct))
}

total_bases <- sum(width(seqs))
mean_length <- mean(width(seqs))
cat(sprintf("Total bases: %d\n", total_bases))
cat(sprintf("Mean length: %.1f\n", mean_length))
cat(sprintf("Total bases (streaming): %d\n", total_bases))

# ============================================================
# 2. VCF — VARIANT CALLS
# ============================================================
cat("\n--- 2. VCF: Variant Calls ---\n")

# Parse VCF manually (VariantAnnotation requires indexed files)
vcf_lines <- readLines("data/variants.vcf")
vcf_lines <- vcf_lines[!grepl("^#", vcf_lines)]

variants <- do.call(rbind, lapply(vcf_lines, function(line) {
  fields <- strsplit(line, "\t")[[1]]
  data.frame(
    chrom = fields[1],
    pos = as.integer(fields[2]),
    id = fields[3],
    ref = fields[4],
    alt = fields[5],
    qual = as.numeric(fields[6]),
    filter = fields[7],
    info = fields[8],
    stringsAsFactors = FALSE
  )
}))

cat(sprintf("Total variants: %d\n", nrow(variants)))
cat(sprintf("First variant: %s:%d %s>%s\n",
            variants$chrom[1], variants$pos[1],
            variants$ref[1], variants$alt[1]))

passed <- variants[variants$filter == "PASS", ]
cat(sprintf("PASS variants: %d\n", nrow(passed)))

snps <- variants[nchar(variants$ref) == 1 & nchar(variants$alt) == 1, ]
indels <- variants[nchar(variants$ref) != nchar(variants$alt), ]
cat(sprintf("SNPs: %d\n", nrow(snps)))
cat(sprintf("Indels: %d\n", nrow(indels)))

chrom_counts <- table(passed$chrom)
cat("\n chrom | count\n")
for (ch in sort(names(chrom_counts))) {
  cat(sprintf(" %-5s | %d\n", ch, chrom_counts[ch]))
}

cat(sprintf("SNPs (streaming): %d\n", nrow(snps)))

# ============================================================
# 3. BED — GENOMIC REGIONS
# ============================================================
cat("\n--- 3. BED: Genomic Regions ---\n")

bed <- read.delim("data/regions.bed", header = FALSE,
                   col.names = c("chrom", "start", "end", "name", "score", "strand"))
cat(sprintf("Regions: %d\n", nrow(bed)))

sizes <- bed$end - bed$start
total_covered <- sum(sizes)
cat(sprintf("Total bases covered: %d\n", total_covered))

chr17 <- bed[bed$chrom == "chr17", ]
cat(sprintf("Chr17 regions: %d\n", nrow(chr17)))

cat("Region sizes:\n")
cat(sprintf("  Min: %d\n", min(sizes)))
cat(sprintf("  Max: %d\n", max(sizes)))
cat(sprintf("  Mean: %.1f\n", mean(sizes)))

# ============================================================
# 4. GFF — GENE ANNOTATIONS
# ============================================================
cat("\n--- 4. GFF: Gene Annotations ---\n")

# Parse GFF manually for this example
gff_lines <- readLines("data/annotations.gff")
gff_lines <- gff_lines[!grepl("^#", gff_lines)]

features <- do.call(rbind, lapply(gff_lines, function(line) {
  fields <- strsplit(line, "\t")[[1]]
  if (length(fields) < 9) return(NULL)

  # Parse attributes
  attrs <- strsplit(fields[9], "; ?")[[1]]
  attr_list <- list()
  for (a in attrs) {
    a <- trimws(gsub(";$", "", a))
    parts <- strsplit(a, " ", fixed = TRUE)[[1]]
    if (length(parts) >= 2) {
      attr_list[[parts[1]]] <- gsub('"', '', parts[2])
    }
  }

  data.frame(
    seqid = fields[1],
    source = fields[2],
    type = fields[3],
    start = as.integer(fields[4]),
    end = as.integer(fields[5]),
    strand = fields[7],
    gene_name = ifelse(is.null(attr_list$gene_name), NA, attr_list$gene_name),
    stringsAsFactors = FALSE
  )
}))

cat(sprintf("Features: %d\n", nrow(features)))

genes <- features[features$type == "gene", ]
exons <- features[features$type == "exon", ]
cds_feat <- features[features$type == "CDS", ]
cat(sprintf("Genes: %d\n", nrow(genes)))
cat(sprintf("Exons: %d\n", nrow(exons)))
cat(sprintf("CDS:   %d\n", nrow(cds_feat)))

gene_names <- genes$gene_name[!is.na(genes$gene_name)]
cat(sprintf("Gene names: [%s]\n", paste(gene_names, collapse = ", ")))

type_counts <- table(features$type)
cat("\n type | count\n")
for (tp in sort(names(type_counts))) {
  cat(sprintf(" %-4s | %d\n", tp, type_counts[tp]))
}

cat(sprintf("Exons (streaming): %d\n", nrow(exons)))

# ============================================================
# 5. BAM — ALIGNMENTS (reading SAM text for this example)
# ============================================================
cat("\n--- 5. BAM: Alignments ---\n")

sam_lines <- readLines("data/alignments.sam")
sam_lines <- sam_lines[!grepl("^@", sam_lines)]

alignments <- do.call(rbind, lapply(sam_lines, function(line) {
  fields <- strsplit(line, "\t")[[1]]
  if (length(fields) < 11) return(NULL)
  flag <- as.integer(fields[2])
  data.frame(
    qname = fields[1],
    flag = flag,
    rname = fields[3],
    pos = as.integer(fields[4]),
    mapq = as.integer(fields[5]),
    cigar = fields[6],
    is_mapped = bitwAnd(flag, 4) == 0,
    stringsAsFactors = FALSE
  )
}))

cat(sprintf("Total alignments: %d\n", nrow(alignments)))

mapped <- alignments[alignments$is_mapped, ]
unmapped <- alignments[!alignments$is_mapped, ]
cat(sprintf("Mapped: %d\n", nrow(mapped)))
cat(sprintf("Unmapped: %d\n", nrow(unmapped)))

mean_mapq <- mean(mapped$mapq)
high_qual <- sum(mapped$mapq >= 30)
cat(sprintf("Mean MAPQ: %.1f\n", mean_mapq))
cat(sprintf("High quality (MAPQ >= 30): %d\n", high_qual))
cat(sprintf("Mapped reads (streaming): %d\n", nrow(mapped)))

# ============================================================
# 6. FORMAT CONVERSIONS
# ============================================================
cat("\n--- 6. Format Conversions ---\n")

# VCF to BED
vcf_bed_start <- variants$pos - 1
vcf_bed_end <- variants$pos - 1 + nchar(variants$ref)
cat(sprintf("VCF -> BED: %d variant intervals\n", nrow(variants)))
cat(sprintf("  First: %s:%d-%d\n", variants$chrom[1], vcf_bed_start[1], vcf_bed_end[1]))

# GFF genes to BED
cat(sprintf("GFF -> BED: %d gene regions\n", nrow(genes)))

# ============================================================
# 7. WRITING OUTPUT
# ============================================================
cat("\n--- 7. Writing Output ---\n")

dir.create("results", showWarnings = FALSE)

# Write FASTA
writeLines(c(">seq1", "ATCGATCG", ">seq2", "GCGCGCGC"), "results/output.fasta")
cat("Wrote 2 sequences to results/output.fasta\n")

# Write BED
write.table(data.frame(chrom = c("chr1", "chr1"), start = c(100, 300), end = c(200, 400)),
            "results/output.bed", sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
cat("Wrote 2 regions to results/output.bed\n")

# Write CSV
result_df <- data.frame(
  gene = c("BRCA1", "TP53", "EGFR"),
  pval = c(0.001, 0.05, 0.003),
  chrom = c("chr17", "chr17", "chr7")
)
write.csv(result_df, "results/output.csv", row.names = FALSE)
cat(sprintf("Wrote %d rows to results/output.csv\n", nrow(result_df)))

# ============================================================
# 8. SUMMARY TABLE
# ============================================================
cat("\n--- 8. Summary ---\n")

summary_data <- data.frame(
  metric = c("Reference sequences", "Total ref bases", "Total variants",
             "PASS variants", "SNPs", "Indels", "BED regions", "Target bases",
             "GFF features", "Genes", "Total alignments", "Mapped reads"),
  value = c(length(seqs), total_bases, nrow(variants),
            nrow(passed), nrow(snps), nrow(indels), nrow(bed), total_covered,
            nrow(features), nrow(genes), nrow(alignments), nrow(mapped))
)

cat(sprintf(" %-22s | value\n", "metric"))
for (i in seq_len(nrow(summary_data))) {
  cat(sprintf(" %-22s | %d\n", summary_data$metric[i], summary_data$value[i]))
}

cat("\n")
cat(strrep("=", 60), "\n")
cat("Day 7 complete! You can now read every major bio format.\n")
cat(strrep("=", 60), "\n")
