#!/usr/bin/env python3
"""Day 7: Bioinformatics File Formats — Python equivalent.
Run: python scripts/analysis.py
Requires: pip install -r python/requirements.txt
Requires: data/ files (generated by init.bl or manually)
"""

from Bio import SeqIO
from Bio.SeqUtils import gc_fraction
import csv
import os
from collections import Counter

print("=" * 60)
print("Day 7: Bioinformatics File Formats (Python)")
print("=" * 60)

# ============================================================
# 1. FASTA — REFERENCE SEQUENCES
# ============================================================
print()
print("--- 1. FASTA: Reference Sequences ---")

seqs = list(SeqIO.parse("data/sequences.fasta", "fasta"))
print(f"Sequences: {len(seqs)}")

for s in seqs:
    gc = gc_fraction(s.seq) * 100
    print(f"  {s.id}: {len(s.seq)} bp, GC={gc:.1f}%")

total_bases = sum(len(s.seq) for s in seqs)
mean_length = total_bases / len(seqs) if seqs else 0
print(f"Total bases: {total_bases}")
print(f"Mean length: {mean_length:.1f}")
print(f"Total bases (streaming): {total_bases}")

# ============================================================
# 2. VCF — VARIANT CALLS
# ============================================================
print()
print("--- 2. VCF: Variant Calls ---")

# Parse VCF manually (pysam VCF requires bgzipped+indexed files)
variants = []
with open("data/variants.vcf") as f:
    for line in f:
        if line.startswith("#"):
            continue
        fields = line.strip().split("\t")
        variants.append({
            "chrom": fields[0],
            "pos": int(fields[1]),
            "id": fields[2],
            "ref": fields[3],
            "alt": fields[4],
            "qual": float(fields[5]),
            "filter": fields[6],
            "info": fields[7],
        })

print(f"Total variants: {len(variants)}")

v = variants[0]
print(f"First variant: {v['chrom']}:{v['pos']} {v['ref']}>{v['alt']}")

passed = [v for v in variants if v["filter"] == "PASS"]
print(f"PASS variants: {len(passed)}")

snps = [v for v in variants if len(v["ref"]) == 1 and len(v["alt"]) == 1]
indels = [v for v in variants if len(v["ref"]) != len(v["alt"])]
print(f"SNPs: {len(snps)}")
print(f"Indels: {len(indels)}")

# Count by chromosome
chrom_counts = Counter(v["chrom"] for v in passed)
print()
print(" chrom | count")
for chrom, count in sorted(chrom_counts.items()):
    print(f" {chrom:<5} | {count}")

snp_count_stream = sum(1 for v in variants if len(v["ref"]) == 1 and len(v["alt"]) == 1)
print(f"SNPs (streaming): {snp_count_stream}")

# ============================================================
# 3. BED — GENOMIC REGIONS
# ============================================================
print()
print("--- 3. BED: Genomic Regions ---")

regions = []
with open("data/regions.bed") as f:
    for line in f:
        fields = line.strip().split("\t")
        regions.append({
            "chrom": fields[0],
            "start": int(fields[1]),
            "end": int(fields[2]),
            "name": fields[3] if len(fields) > 3 else "",
            "score": int(fields[4]) if len(fields) > 4 else 0,
            "strand": fields[5] if len(fields) > 5 else ".",
        })

print(f"Regions: {len(regions)}")

total_covered = sum(r["end"] - r["start"] for r in regions)
print(f"Total bases covered: {total_covered}")

chr17 = [r for r in regions if r["chrom"] == "chr17"]
print(f"Chr17 regions: {len(chr17)}")

sizes = [r["end"] - r["start"] for r in regions]
print(f"Region sizes:")
print(f"  Min: {min(sizes)}")
print(f"  Max: {max(sizes)}")
print(f"  Mean: {sum(sizes) / len(sizes):.1f}")

# ============================================================
# 4. GFF — GENE ANNOTATIONS
# ============================================================
print()
print("--- 4. GFF: Gene Annotations ---")

features = []
with open("data/annotations.gff") as f:
    for line in f:
        if line.startswith("#"):
            continue
        fields = line.strip().split("\t")
        if len(fields) < 9:
            continue
        attrs = {}
        for pair in fields[8].split("; "):
            pair = pair.strip().rstrip(";")
            if " " in pair:
                key, val = pair.split(" ", 1)
                attrs[key] = val.strip('"')
        features.append({
            "seqid": fields[0],
            "source": fields[1],
            "type": fields[2],
            "start": int(fields[3]),
            "end": int(fields[4]),
            "strand": fields[6],
            "attributes": attrs,
        })

print(f"Features: {len(features)}")

genes = [f for f in features if f["type"] == "gene"]
exons = [f for f in features if f["type"] == "exon"]
cds = [f for f in features if f["type"] == "CDS"]
print(f"Genes: {len(genes)}")
print(f"Exons: {len(exons)}")
print(f"CDS:   {len(cds)}")

gene_names = [g["attributes"].get("gene_name", "?") for g in genes]
print(f"Gene names: {gene_names}")

type_counts = Counter(f["type"] for f in features)
print()
print(" type | count")
for t, c in sorted(type_counts.items()):
    print(f" {t:<4} | {c}")

exon_count_stream = sum(1 for f in features if f["type"] == "exon")
print(f"Exons (streaming): {exon_count_stream}")

# ============================================================
# 5. BAM — ALIGNMENTS (reading SAM text for this example)
# ============================================================
print()
print("--- 5. BAM: Alignments ---")

alignments = []
with open("data/alignments.sam") as f:
    for line in f:
        if line.startswith("@"):
            continue
        fields = line.strip().split("\t")
        if len(fields) < 11:
            continue
        flag = int(fields[1])
        mapq = int(fields[4])
        is_mapped = (flag & 4) == 0
        alignments.append({
            "qname": fields[0],
            "flag": flag,
            "rname": fields[2],
            "pos": int(fields[3]),
            "mapq": mapq,
            "cigar": fields[5],
            "is_mapped": is_mapped,
        })

print(f"Total alignments: {len(alignments)}")

mapped = [a for a in alignments if a["is_mapped"]]
unmapped = [a for a in alignments if not a["is_mapped"]]
print(f"Mapped: {len(mapped)}")
print(f"Unmapped: {len(unmapped)}")

mapqs = [a["mapq"] for a in mapped]
mean_mapq = sum(mapqs) / len(mapqs) if mapqs else 0
high_qual = sum(1 for q in mapqs if q >= 30)
print(f"Mean MAPQ: {mean_mapq:.1f}")
print(f"High quality (MAPQ >= 30): {high_qual}")
print(f"Mapped reads (streaming): {len(mapped)}")

# ============================================================
# 6. FORMAT CONVERSIONS
# ============================================================
print()
print("--- 6. Format Conversions ---")

# VCF to BED
vcf_beds = [
    {"chrom": v["chrom"], "start": v["pos"] - 1, "end": v["pos"] - 1 + len(v["ref"])}
    for v in variants
]
print(f"VCF -> BED: {len(vcf_beds)} variant intervals")
first_bed = vcf_beds[0]
print(f"  First: {first_bed['chrom']}:{first_bed['start']}-{first_bed['end']}")

# GFF genes to BED
gene_beds = [
    {"chrom": g["seqid"], "start": g["start"] - 1, "end": g["end"],
     "name": g["attributes"].get("gene_name", "")}
    for g in genes
]
print(f"GFF -> BED: {len(gene_beds)} gene regions")

# ============================================================
# 7. WRITING OUTPUT
# ============================================================
print()
print("--- 7. Writing Output ---")

os.makedirs("results", exist_ok=True)

# Write FASTA
with open("results/output.fasta", "w") as f:
    f.write(">seq1\nATCGATCG\n>seq2\nGCGCGCGC\n")
print("Wrote 2 sequences to results/output.fasta")

# Write BED
with open("results/output.bed", "w") as f:
    f.write("chr1\t100\t200\nchr1\t300\t400\n")
print("Wrote 2 regions to results/output.bed")

# Write CSV
with open("results/output.csv", "w", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=["gene", "pval", "chrom"])
    writer.writeheader()
    writer.writerow({"gene": "BRCA1", "pval": 0.001, "chrom": "chr17"})
    writer.writerow({"gene": "TP53", "pval": 0.05, "chrom": "chr17"})
    writer.writerow({"gene": "EGFR", "pval": 0.003, "chrom": "chr7"})
print("Wrote 3 rows to results/output.csv")

# ============================================================
# 8. SUMMARY TABLE
# ============================================================
print()
print("--- 8. Summary ---")

summary = [
    ("Reference sequences", len(seqs)),
    ("Total ref bases", total_bases),
    ("Total variants", len(variants)),
    ("PASS variants", len(passed)),
    ("SNPs", len(snps)),
    ("Indels", len(indels)),
    ("BED regions", len(regions)),
    ("Target bases", total_covered),
    ("GFF features", len(features)),
    ("Genes", len(genes)),
    ("Total alignments", len(alignments)),
    ("Mapped reads", len(mapped)),
]

print(f" {'metric':<22} | value")
for metric, value in summary:
    print(f" {metric:<22} | {value}")

print()
print("=" * 60)
print("Day 7 complete! You can now read every major bio format.")
print("=" * 60)
